### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by shivam-bathla** [sullo/other-tools#1]
Hi @sullo,

Thanks for all the great work! This repo contains some really handy scripts :)
I really appreciate your work and efforts for the infosec community. Could you please mention the license information for this project (GPL / MIT, etc). That would be really helpful.

Thanks!

**Comment by sullo** [comment]
Per the COPYING file and comments in the code, the program is licensed under the GPL

https://github.com/sullo/nikto/blob/master/COPYING

Note that the databases have a more restricted license as described in the header of each file.
